name: apptubes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  image: ^4.1.3
  tflite_flutter: ^0.11.0
  http: ^1.2.1
  # tflite_flutter_helper: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/food_info.json
    - assets/labels.txt
    - assets/food_classifier_flex.tflite
